spring:
  datasource:
    url: jdbc:postgresql://dpg-d5mviskmrvns73fe923g-a:5432/online_school_bb1t
    username: postgres1
    password: 2dUPokplrf8HVR7nLUuvaGBbHaY7dPWb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080

minio:
  enabled: false

cloudinary:
  cloud-name: dvbej3gbu
  api-key: 125476794446191
  api-secret: SZSaROkvF3DGdpt4P4sgCdj8RqI
