spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OnlineSchoolWeb2?connectTimeout=60&socketTimeout=60&tcpKeepAlive=true&ApplicationName=OnlineSchoolKursach
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080